#!/usr/bin/env python3
from robyn import Robyn
from asyncio import sleep
from random import uniform

app = Robyn(__file__)

MSG_ID = 0
COUNT = 0

@app.get('/')
async def hello_world(_):
    return 'Hello, world!\n'

@app.get('/:code/:delay')
async def webhook_post(r):
    global MSG_ID, COUNT
    code = r['params']['code']
    delay = r['params']['delay']

    # Allocate msg_id
    MSG_ID += 1
    msg_id = MSG_ID

    if code == '_':
        is_random_code = True
        code = 200 if uniform(0, 1) > 0.3 else 500
    else:
        is_random_code = False
        code = int(code)


    if delay == '_':
        is_random_delay = True
        delay = uniform(0, 20)
    else:
        is_random_delay = False
        delay = float(delay)

    # Delay
    await sleep(delay)

    # Log message
    COUNT += 1
    # TODO: support POST
    print(f'''{COUNT=:<8}{msg_id=:<8}GET    {code=}{' (random)' if is_random_code else ''}   {delay=}{' (random)' if is_random_delay else ''}''')
    # TODO: status code
    return 'OK\n'

app.start(port=5000, url='0.0.0.0')
